import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const OPENLOOM_EXPERIMENTAL = truthy("OPENLOOM_EXPERIMENTAL")
const copy = process.env["OPENLOOM_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OPENLOOM_AUTO_HEAP_SNAPSHOT: truthy("OPENLOOM_AUTO_HEAP_SNAPSHOT"),
  OPENLOOM_GIT_BASH_PATH: process.env["OPENLOOM_GIT_BASH_PATH"],
  OPENLOOM_CONFIG: process.env["OPENLOOM_CONFIG"],
  OPENLOOM_CONFIG_CONTENT: process.env["OPENLOOM_CONFIG_CONTENT"],
  OPENLOOM_DISABLE_AUTOUPDATE: truthy("OPENLOOM_DISABLE_AUTOUPDATE"),
  OPENLOOM_ALWAYS_NOTIFY_UPDATE: truthy("OPENLOOM_ALWAYS_NOTIFY_UPDATE"),
  OPENLOOM_DISABLE_PRUNE: truthy("OPENLOOM_DISABLE_PRUNE"),
  OPENLOOM_DISABLE_TERMINAL_TITLE: truthy("OPENLOOM_DISABLE_TERMINAL_TITLE"),
  OPENLOOM_SHOW_TTFD: truthy("OPENLOOM_SHOW_TTFD"),
  OPENLOOM_PERMISSION: process.env["OPENLOOM_PERMISSION"],
  OPENLOOM_DISABLE_AUTOCOMPACT: truthy("OPENLOOM_DISABLE_AUTOCOMPACT"),
  OPENLOOM_DISABLE_MODELS_FETCH: truthy("OPENLOOM_DISABLE_MODELS_FETCH"),
  OPENLOOM_DISABLE_MOUSE: truthy("OPENLOOM_DISABLE_MOUSE"),
  OPENLOOM_FAKE_VCS: process.env["OPENLOOM_FAKE_VCS"],
  OPENLOOM_SERVER_PASSWORD: process.env["OPENLOOM_SERVER_PASSWORD"],
  OPENLOOM_SERVER_USERNAME: process.env["OPENLOOM_SERVER_USERNAME"],

  // Experimental
  OPENLOOM_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENLOOM_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENLOOM_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENLOOM_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENLOOM_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("OPENLOOM_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENLOOM_MODELS_URL: process.env["OPENLOOM_MODELS_URL"],
  OPENLOOM_MODELS_PATH: process.env["OPENLOOM_MODELS_PATH"],
  OPENLOOM_DB: process.env["OPENLOOM_DB"],

  OPENLOOM_WORKSPACE_ID: process.env["OPENLOOM_WORKSPACE_ID"],
  OPENLOOM_EXPERIMENTAL_WORKSPACES: OPENLOOM_EXPERIMENTAL || truthy("OPENLOOM_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get OPENLOOM_DISABLE_PROJECT_CONFIG() {
    return truthy("OPENLOOM_DISABLE_PROJECT_CONFIG")
  },
  get OPENLOOM_TUI_CONFIG() {
    return process.env["OPENLOOM_TUI_CONFIG"]
  },
  get OPENLOOM_CONFIG_DIR() {
    return process.env["OPENLOOM_CONFIG_DIR"]
  },
  get OPENLOOM_PURE() {
    return truthy("OPENLOOM_PURE")
  },
  get OPENLOOM_PLUGIN_META_FILE() {
    return process.env["OPENLOOM_PLUGIN_META_FILE"]
  },
  get OPENLOOM_CLIENT() {
    return process.env["OPENLOOM_CLIENT"] ?? "cli"
  },
}
